# Copyright (c) 2025 ADBC Drivers Contributors
# Copyright (c) 2026 SingleStore, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 5ba58aca0bd5bc7c0e1c0fc45af2e88d6a2bde83  # frozen: v0.14.10
  hooks:
    - id: ruff-check
      name: "ruff check (isort)"
      args: ["--select", "I", "--fix"]
    - id: ruff-check
      args: ["--fix"]
    - id: ruff-format

- repo: https://github.com/codespell-project/codespell
  rev: 63c8f8312b7559622c0d82815639671ae42132ac  # v2.4.1
  hooks:
  - id: codespell
    exclude: >
        (?x)^(
            .*go\.sum|
            LICENSE\.txt
        )$

- repo: https://github.com/golangci/golangci-lint
  rev: 9f61b0f53f80672872fced07b6874397c3ed197b  # frozen: v2.7.2
  hooks:
  - id: golangci-lint
    name: lint
    entry: bash -c 'cd go && golangci-lint run --fix --timeout 5m'
    types_or: [go, go-mod]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-yaml
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: [--fix=lf]
    exclude: '\.bat$'
  - id: trailing-whitespace

- repo: https://github.com/adbc-drivers/dev
  rev: 507c0ce1523d79237fe7d7e158e092e2b499df34
  hooks:
  - id: rat
