// Code generated by _tmpl/utils.h.tmpl. DO NOT EDIT.

// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// clang-format off
//go:build driverlib
// clang-format on

#pragma once

#include "adbc.h"
#include <stdlib.h>

struct AdbcError* SingleStoreErrorFromArrayStream(struct ArrowArrayStream*,
                                                  AdbcStatusCode*);
AdbcStatusCode SingleStoreDatabaseGetOption(struct AdbcDatabase*, const char*, char*,
                                            size_t*, struct AdbcError*);
AdbcStatusCode SingleStoreDatabaseGetOptionBytes(struct AdbcDatabase*, const char*,
                                                 uint8_t*, size_t*, struct AdbcError*);
AdbcStatusCode SingleStoreDatabaseGetOptionDouble(struct AdbcDatabase*, const char*,
                                                  double*, struct AdbcError*);
AdbcStatusCode SingleStoreDatabaseGetOptionInt(struct AdbcDatabase*, const char*,
                                               int64_t*, struct AdbcError*);
AdbcStatusCode SingleStoreDatabaseInit(struct AdbcDatabase* db, struct AdbcError* err);
AdbcStatusCode SingleStoreDatabaseNew(struct AdbcDatabase* db, struct AdbcError* err);
AdbcStatusCode SingleStoreDatabaseRelease(struct AdbcDatabase* db, struct AdbcError* err);
AdbcStatusCode SingleStoreDatabaseSetOption(struct AdbcDatabase* db, const char* key,
                                            const char* value, struct AdbcError* err);
AdbcStatusCode SingleStoreDatabaseSetOptionBytes(struct AdbcDatabase*, const char*,
                                                 const uint8_t*, size_t,
                                                 struct AdbcError*);
AdbcStatusCode SingleStoreDatabaseSetOptionDouble(struct AdbcDatabase*, const char*,
                                                  double, struct AdbcError*);
AdbcStatusCode SingleStoreDatabaseSetOptionInt(struct AdbcDatabase*, const char*, int64_t,
                                               struct AdbcError*);

AdbcStatusCode SingleStoreConnectionCancel(struct AdbcConnection*, struct AdbcError*);
AdbcStatusCode SingleStoreConnectionCommit(struct AdbcConnection* cnxn,
                                           struct AdbcError* err);
AdbcStatusCode SingleStoreConnectionGetInfo(struct AdbcConnection* cnxn,
                                            const uint32_t* codes, size_t len,
                                            struct ArrowArrayStream* out,
                                            struct AdbcError* err);
AdbcStatusCode SingleStoreConnectionGetObjects(
    struct AdbcConnection* cnxn, int depth, const char* catalog, const char* dbSchema,
    const char* tableName, const char** tableType, const char* columnName,
    struct ArrowArrayStream* out, struct AdbcError* err);
AdbcStatusCode SingleStoreConnectionGetOption(struct AdbcConnection*, const char*, char*,
                                              size_t*, struct AdbcError*);
AdbcStatusCode SingleStoreConnectionGetOptionBytes(struct AdbcConnection*, const char*,
                                                   uint8_t*, size_t*, struct AdbcError*);
AdbcStatusCode SingleStoreConnectionGetOptionDouble(struct AdbcConnection*, const char*,
                                                    double*, struct AdbcError*);
AdbcStatusCode SingleStoreConnectionGetOptionInt(struct AdbcConnection*, const char*,
                                                 int64_t*, struct AdbcError*);
AdbcStatusCode SingleStoreConnectionGetStatistics(struct AdbcConnection*, const char*,
                                                  const char*, const char*, char,
                                                  struct ArrowArrayStream*,
                                                  struct AdbcError*);
AdbcStatusCode SingleStoreConnectionGetStatisticNames(struct AdbcConnection*,
                                                      struct ArrowArrayStream*,
                                                      struct AdbcError*);
AdbcStatusCode SingleStoreConnectionGetTableSchema(
    struct AdbcConnection* cnxn, const char* catalog, const char* dbSchema,
    const char* tableName, struct ArrowSchema* schema, struct AdbcError* err);
AdbcStatusCode SingleStoreConnectionGetTableTypes(struct AdbcConnection* cnxn,
                                                  struct ArrowArrayStream* out,
                                                  struct AdbcError* err);
AdbcStatusCode SingleStoreConnectionInit(struct AdbcConnection* cnxn,
                                         struct AdbcDatabase* db, struct AdbcError* err);
AdbcStatusCode SingleStoreConnectionNew(struct AdbcConnection* cnxn,
                                        struct AdbcError* err);
AdbcStatusCode SingleStoreConnectionReadPartition(struct AdbcConnection* cnxn,
                                                  const uint8_t* serialized,
                                                  size_t serializedLen,
                                                  struct ArrowArrayStream* out,
                                                  struct AdbcError* err);
AdbcStatusCode SingleStoreConnectionRelease(struct AdbcConnection* cnxn,
                                            struct AdbcError* err);
AdbcStatusCode SingleStoreConnectionRollback(struct AdbcConnection* cnxn,
                                             struct AdbcError* err);
AdbcStatusCode SingleStoreConnectionSetOption(struct AdbcConnection* cnxn,
                                              const char* key, const char* val,
                                              struct AdbcError* err);
AdbcStatusCode SingleStoreConnectionSetOptionBytes(struct AdbcConnection*, const char*,
                                                   const uint8_t*, size_t,
                                                   struct AdbcError*);
AdbcStatusCode SingleStoreConnectionSetOptionDouble(struct AdbcConnection*, const char*,
                                                    double, struct AdbcError*);
AdbcStatusCode SingleStoreConnectionSetOptionInt(struct AdbcConnection*, const char*,
                                                 int64_t, struct AdbcError*);

AdbcStatusCode SingleStoreStatementBind(struct AdbcStatement* stmt,
                                        struct ArrowArray* values,
                                        struct ArrowSchema* schema,
                                        struct AdbcError* err);
AdbcStatusCode SingleStoreStatementBindStream(struct AdbcStatement* stmt,
                                              struct ArrowArrayStream* stream,
                                              struct AdbcError* err);
AdbcStatusCode SingleStoreStatementCancel(struct AdbcStatement*, struct AdbcError*);
AdbcStatusCode SingleStoreStatementExecuteQuery(struct AdbcStatement* stmt,
                                                struct ArrowArrayStream* out,
                                                int64_t* affected, struct AdbcError* err);
AdbcStatusCode SingleStoreStatementExecutePartitions(struct AdbcStatement* stmt,
                                                     struct ArrowSchema* schema,
                                                     struct AdbcPartitions* partitions,
                                                     int64_t* affected,
                                                     struct AdbcError* err);
AdbcStatusCode SingleStoreStatementExecutePartitionsTrampoline(
    struct AdbcStatement* stmt, struct ArrowSchema* schema,
    struct AdbcPartitions* partitions, int64_t* affected, struct AdbcError* err);
AdbcStatusCode SingleStoreStatementExecuteSchema(struct AdbcStatement*,
                                                 struct ArrowSchema*, struct AdbcError*);
AdbcStatusCode SingleStoreStatementGetOption(struct AdbcStatement*, const char*, char*,
                                             size_t*, struct AdbcError*);
AdbcStatusCode SingleStoreStatementGetOptionBytes(struct AdbcStatement*, const char*,
                                                  uint8_t*, size_t*, struct AdbcError*);
AdbcStatusCode SingleStoreStatementGetOptionDouble(struct AdbcStatement*, const char*,
                                                   double*, struct AdbcError*);
AdbcStatusCode SingleStoreStatementGetOptionInt(struct AdbcStatement*, const char*,
                                                int64_t*, struct AdbcError*);
AdbcStatusCode SingleStoreStatementGetParameterSchema(struct AdbcStatement* stmt,
                                                      struct ArrowSchema* schema,
                                                      struct AdbcError* err);
AdbcStatusCode SingleStoreStatementNew(struct AdbcConnection* cnxn,
                                       struct AdbcStatement* stmt, struct AdbcError* err);
AdbcStatusCode SingleStoreStatementPrepare(struct AdbcStatement* stmt,
                                           struct AdbcError* err);
AdbcStatusCode SingleStoreStatementRelease(struct AdbcStatement* stmt,
                                           struct AdbcError* err);
AdbcStatusCode SingleStoreStatementSetOption(struct AdbcStatement* stmt, const char* key,
                                             const char* value, struct AdbcError* err);
AdbcStatusCode SingleStoreStatementSetOptionBytes(struct AdbcStatement*, const char*,
                                                  const uint8_t*, size_t,
                                                  struct AdbcError*);
AdbcStatusCode SingleStoreStatementSetOptionDouble(struct AdbcStatement*, const char*,
                                                   double, struct AdbcError*);
AdbcStatusCode SingleStoreStatementSetOptionInt(struct AdbcStatement*, const char*,
                                                int64_t, struct AdbcError*);
AdbcStatusCode SingleStoreStatementSetSqlQuery(struct AdbcStatement* stmt,
                                               const char* query, struct AdbcError* err);
AdbcStatusCode SingleStoreStatementSetSubstraitPlan(struct AdbcStatement* stmt,
                                                    const uint8_t* plan, size_t length,
                                                    struct AdbcError* err);

AdbcStatusCode AdbcDriverSingleStoreInit(int version, void* rawDriver,
                                         struct AdbcError* err);

static inline void SingleStoreerrRelease(struct AdbcError* error) {
  if (error->release) {
    error->release(error);
    error->release = NULL;
  }
}

void SingleStore_release_error(struct AdbcError* error);

struct SingleStoreError {
  char* message;
  char** keys;
  uint8_t** values;
  size_t* lengths;
  int count;
};

void SingleStoreReleaseErrWithDetails(struct AdbcError* error);

int SingleStoreErrorGetDetailCount(const struct AdbcError* error);
struct AdbcErrorDetail SingleStoreErrorGetDetail(const struct AdbcError* error,
                                                 int index);

int SingleStoreArrayStreamGetSchemaTrampoline(struct ArrowArrayStream* stream,
                                              struct ArrowSchema* out);
int SingleStoreArrayStreamGetNextTrampoline(struct ArrowArrayStream* stream,
                                            struct ArrowArray* out);
